const AUTHENTICATE_ROUTE = {
  REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
  LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  FPW_VERIFY_OTP: '@AUTHENTICATE_ROUTE/FPW_VERIFY_OTP',
};
const ONBOARDING_ROUTE = {
  INPUT_NAME: '@ONBOARDING_ROUTE/INPUT_NAME',
};
const APP_ROUTE = {
  MAIN_TAB: '@APP_ROUTE/MAIN_TAB',
  HOME_TAB: '@APP_ROUTE/MAIN_TAB/HOME_TAB',
};
export {APP_ROUTE, AUTHENTICATE_ROUTE, ONBOARDING_ROUTE};
