const AUTHENTICATE_ROUTE = {
    REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
    FPW_VERIFY_OTP: '@AUTHENTICATE_ROUTE/FPW_VERIFY_OTP',
};

const APP_ROUTE = {
    MAIN_TAB: '@APP_ROUTE/MAIN_TAB',
    HOME_TAB: '@APP_ROUTE/MAIN_TAB/HOME_TAB',
  };
  export {
    APP_ROUTE,
    AUTHENTICATE_ROUTE,
  };